### PR TITLE
November update for Impl Status

### PR DESCRIPTION
**Pull request by ibelem**
@anssiko PTAL

Plan to update WebNN [browser-compat-data](https://github.com/mdn/browser-compat-data) base on this version.

### CODE REVIEW

**Review by anssiko — APPROVED** [review]
LGTM!

While here, do you think we should reflect the [TFLite -> LiteRT rename](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/) into this status tracker in a future update?

I'm fine keeping the JSON keys as is if this rename would be tedious and only update the visible parts.

**Comment by ibelem** [comment]
Great suggestion @anssiko , updated in https://github.com/webmachinelearning/webmachinelearning.github.io/pull/84/commits/7bc522d715181f61024a4a129a706bfd1fb46ccd PTAL

**Review by anssiko — APPROVED** [review]
Changes look good to me, thanks! Do you want to merge this now, or coordinate with BCD changes?

**Comment by ibelem** [comment]
@anssiko Please help to merge it directly. I will submit new BCD PR tomorrow. Thanks!

**Pull request merged**
