### PR TITLE
Add a new Incubations page and update Community page

### PR DESCRIPTION
**Pull request by anssiko**
Incubations page replaces the old Model Loader page. This update also updates the Community page to reflect recent changes. Gemfile.lock is also updated, bumping versions and in some cases also specifying looser dependencies.

### CODE REVIEW

**Comment by anssiko** [comment]
PTAL @ibelem

I tested this locally. It is good that you also try this out before we deploy. Note the updated dependencies.

**Comment by ibelem** [comment]
Thanks @anssiko for the update, LGTM for the contents. Tested with old Gemfile.lock. 

About the environment by using the new Gemfile.lock in your PR, I always encounter the following error even run the seperate installation manually on test machine. If the issue doesn't occur on Github CI, please skip it. 

```
belem@int:~/github/webmachinelearning.github.io$ bundle exec jekyll serve
Could not find sass-embedded-1.82.0-x86_64-linux-gnu in locally installed gems
```

```
bundle install
gem uninstall sass-embedded -v 1.71.1
gem install sass-embedded -v 1.82.0
```

**Review by ibelem — APPROVED** [review]

**Comment by anssiko** [comment]
@ibelem much thanks for checking in a test environment. I pushed an update to this PR without any Gemfile.lock changes.

We could investigate what breaks in dependencies separately.

**Comment by anssiko** [comment]
Deploy success: https://webmachinelearning.github.io/incubations/

There was one warning:
>[build](https://github.com/webmachinelearning/webmachinelearning.github.io/actions/runs/12293312318/job/34305750450)
The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/

**Pull request merged**
