### PR TITLE
Architecture diagram and How to Get Started change

### PR DESCRIPTION
**Pull request by ibelem**
1. Continue to update architecture diagram, hover the WebNN could show correct up to down paths
2. Updated "How to Get Started"
   - WebNN polyfill is not that necessary anymore
   - WebNN Native is not our focus 

@anssiko PTAL

### CODE REVIEW

**Comment by huningxin** [comment]
@ibelem , thanks for your PR! Is there a preview I can take a look?

**Comment by ibelem** [comment]
Screenshot 2024-05-20 153437

@huningxin PTAL the preview, no hover and with hover effect.

Screenshot 2024-05-20 153502

**Review by huningxin — APPROVED** [review]
LGTM, thanks!

**Review by anssiko — APPROVED** [review]
Great updates, thank you!

**Pull request merged**
