### PR TITLE
WebNN Implementation Status Update

### LINKED ISSUE #57: Update recent WebNN DirectML implementation status
`anssik: I wanted to check if there are implementation status updates to share with the WG`

I will update the WebNN DirectML implementation status and XNNPack, ORT status in next week. @anssiko

### PR DESCRIPTION
**Pull request by ibelem**
Updated WebNN Implementation Status to Nov 21, fix #57 

- WebNN CPU XNNPack backend
- WebNN GPU DirectML backend
- ORT

@lisa0314 @miaobin @Honry @mingmingtasd @BruceDai @shiyi9801 PTAL

10 239 115 52_4000_webnn-status_ (1)

### CODE REVIEW

**Comment by anssiko** [comment]
Thanks @ibelem, please ping me when the team has reviewed this data for accuracy so we can merge at earlier opportunity.

**Comment by Honry** [comment]
@ibelem, thanks for the update, one comment that we have `Where` supported in WebNN EP based on WebNN op `elementwise`.

**Comment by ibelem** [comment]
Thanks and integrated @lisa0314 @Honry @mingmingtasd and @BruceDai 's feedback. @anssiko please help to review and merge this update, and we can expect 10+ ops / directml landing in next week, will continute to update the status. :)

**Comment by anssiko** [comment]
Thanks you @lisa0314 @Honry @mingmingtasd @BruceDai @ibelem for your continued work on keeping this implementation status updated! This resource is super helpful not just for the W3C WG but for the wider web ecosystem, including for early adopter web and framework developers.

**Pull request merged**
