### PR TITLE
Using percentage in the implementation status of WebNN operations indicator

### LINKED ISSUE #47: Using percentage in the implementation status of WebNN operations indicator
By @anssiko in https://github.com/webmachinelearning/webmachinelearning.github.io/pull/46

> The usual definition of done would be spec_total == x_total (or 100%), so I'd increase the counter only by one for e.g. concat impl when the entire concat impl task is done IOW spec_total >= x_total is always true. Maybe a percentage would be better indicator of doneness in this context?

### PR DESCRIPTION
**Pull request by ibelem**
Fix #47 .

@anssiko the total count of the v1 ops defined in spec is 60, PTAL.

10 239 115 52_4000_webnn-status_ (2)

### CODE REVIEW

**Comment by anssiko** [comment]
Thanks!

**Comment by anssiko** [comment]
@ibelem minor typo s/Not Support/Not Supported/g

**Comment by ibelem** [comment]
@anssiko , The "Not Support" here means the ops defined in the spec can not be impleneted on the backend like XNNPack due to the limitations, it does not nean we can support these ops later. Please correct me. 

- The "Not Supported" == "Planning", "Planned" and "Work in Progress".
- The "Not Support" == "Unable to Implement".

**Comment by anssiko** [comment]
”Not Supported” with a footnote to explain the reason where applicable? From a web developer’s PoV it doesn’t matter why something is not supported so I’d put the answer to ”why” into a footnote.

**Comment by ibelem** [comment]
Thanks @anssiko, double checked the MDN and caniuse.com. I think it's necessary to explain the reason, I will change the s/Not Support/Not Supported/g at first.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API 
https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md 

- Full support
- Partial support
- No support
- Experimental. Expect behavior to change in the future.
- See implementation notes.
- User must explicitly enable this feature.
- Has more compatibility info.

https://caniuse.com/css-grid
- Supported
- Not Supported

**Pull request merged**
